# action.yml
name: 'Build in docker'
description: 'Build the whole project'

inputs:
  VITE_SUPPORT_MAIL:
    description: 'Support mail'
    required: true

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    VITE_SUPPORT_MAIL: ${{ inputs.VITE_SUPPORT_MAIL }}